# Generated by Django 3.2.9 on 2021-11-12 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cast', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('poster_image', models.ImageField(upload_to='movie_poster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeriesCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cast_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cast.cast')),
                ('series_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='series.series')),
            ],
        ),
        migrations.AddField(
            model_name='series',
            name='casts',
            field=models.ManyToManyField(related_name='series', through='series.SeriesCast', to='cast.Cast'),
        ),
    ]
